# Generated by Django 4.1 on 2022-11-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
