# Generated by Django 4.1 on 2022-11-14 07:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_profiles_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiles',
            new_name='Profile',
        ),
    ]
