# Generated by Django 4.1 on 2023-01-07 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_location_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_tweeter',
            new_name='social_twitter',
        ),
    ]
